import React, { useEffect, useMemo, useState } from 'react';
import { Download, Heart, Headphones, Library, TrendingUp } from 'lucide-react';
import UserSingleton from '../../Model/UserSingleton';
import { BeatPost, fetchProducerPosts } from '../../Model/api/posts';
import { CardSkeleton, EmptyState, ErrorState } from '../../components/States/EmptyState';
import { formatCompactNumber, getBeatId, getCoverUrl } from '../../utils/entities';
import './Stats.css';

export default function Stats() {
  const username = UserSingleton.getInstance().getUsername(); const [beats, setBeats] = useState<BeatPost[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { const controller = new AbortController(); fetchProducerPosts('', username, 100, 0, controller.signal).then(setBeats).catch((err) => { if (!controller.signal.aborted) setError(err instanceof Error ? err.message : 'Unable to load stats.') }).finally(() => { if (!controller.signal.aborted) setLoading(false) }); return () => controller.abort() }, [username]);
  const totals = useMemo(() => ({ plays: beats.reduce((s,b) => s + (b.views || b.plays || 0),0), likes: beats.reduce((s,b) => s+b.likes,0), saves: beats.reduce((s,b) => s+b.saves,0), week: beats.reduce((s,b) => s+(b.plays_7d || 0),0) }), [beats]);
  const ranked = useMemo(() => [...beats].sort((a,b) => (b.views || b.plays || 0) - (a.views || a.plays || 0)), [beats]);
  const exportCsv = () => { const headers = ['id','title','publication_date','plays','likes','saves']; const lines = beats.map((beat) => [getBeatId(beat), beat.title, beat.publication_date, beat.views || beat.plays || 0, beat.likes, beat.saves].map((value) => `"${String(value).replace(/"/g,'""')}"`).join(',')); const url = URL.createObjectURL(new Blob([[headers.join(','),...lines].join('\n')],{type:'text/csv'})); const link=document.createElement('a');link.href=url;link.download=`${username}-stats.csv`;link.click();URL.revokeObjectURL(url) };
  if (loading) return <div className="page"><CardSkeleton count={8} /></div>;
  if (error) return <div className="page"><ErrorState message={error} /></div>;
  return <div className="page stats-page"><header className="page-header"><div><p className="page-eyebrow">Performance</p><h1 className="page-title">Your numbers</h1><p className="page-subtitle">A clear snapshot of how your catalog is performing.</p></div><button className="button button--secondary" type="button" onClick={exportCsv} disabled={!beats.length}><Download size={18} />Export CSV</button></header><section className="stats-metrics"><article><Headphones /><span>Total plays</span><strong>{formatCompactNumber(totals.plays)}</strong><small>{formatCompactNumber(totals.week)} in the last 7 days</small></article><article><Heart /><span>Likes</span><strong>{formatCompactNumber(totals.likes)}</strong><small>Across {beats.length} beats</small></article><article><Library /><span>Saves</span><strong>{formatCompactNumber(totals.saves)}</strong><small>{totals.plays ? ((totals.saves/totals.plays)*100).toFixed(1) : '0.0'}% save rate</small></article><article><TrendingUp /><span>Catalog</span><strong>{beats.length}</strong><small>Published beats</small></article></section><div className="section-header"><div><h2>Top performing beats</h2><p>Ranked by total plays</p></div></div>{ranked.length ? <div className="ranking-list">{ranked.map((beat,index) => <article key={getBeatId(beat)}><span className="ranking-number">{String(index+1).padStart(2,'0')}</span><img src={getCoverUrl(beat)} onError={(e) => {e.currentTarget.src='/cover-fallback.svg'}} alt="" loading="lazy"/><div><strong>{beat.title}</strong><span>{beat.genre || 'No genre'} · {beat.bpm ? `${beat.bpm} BPM` : 'Tempo not set'}</span></div><dl><div><dt>Plays</dt><dd>{formatCompactNumber(beat.views || beat.plays || 0)}</dd></div><div><dt>Likes</dt><dd>{beat.likes}</dd></div><div><dt>Saves</dt><dd>{beat.saves}</dd></div></dl></article>)}</div> : <EmptyState title="No performance data yet" message="Publish a beat to start tracking activity." />}</div>;
}
