import React, { FormEvent, useMemo, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import logo2 from '../../assets/Frame 2.png';
import AuthLayout from '../../components/AuthLayout/AuthLayout';
import CustomPopup from '../../components/Popup/CustomPopup';
import { confirmPasswordReset, requestPasswordReset } from '../../Model/api/auth';

export default function ForgotPwdPage() {
  const navigate=useNavigate();const location=useLocation();const token=useMemo(()=>new URLSearchParams(location.search).get('token')||'',[location.search]);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [confirmPassword,setConfirmPassword]=useState('');const [message,setMessage]=useState('');const [loading,setLoading]=useState(false);const [success,setSuccess]=useState(false);
  const submit=async(event:FormEvent)=>{event.preventDefault();if(loading)return;setLoading(true);try{if(token){if(password.length<8||password.length>128)throw new Error('Password must be 8-128 characters.');if(password!==confirmPassword)throw new Error('Passwords do not match.');await confirmPasswordReset(token,password);setSuccess(true);setMessage('Password changed. You can sign in now.')}else{if(!/\S+@\S+\.\S+/.test(email))throw new Error('Enter a valid email address.');await requestPasswordReset(email);setMessage('If this email exists, reset instructions are on their way.')}}catch(err){setMessage(err instanceof Error?err.message:'The request could not be completed.')}finally{setLoading(false)}};
  return <div className="app">{message&&<CustomPopup message={message} onClose={()=>{setMessage('');if(success)navigate('/login')}}/>}<AuthLayout illustration={<img className="auth-illustration" src={logo2} alt="BeatNow illustration"/>}><div className="auth-content"><div><p className="page-eyebrow">Account recovery</p><h1 className="auth-title">{token?'Choose a new password.':'Reset your password.'}</h1><p className="auth-subtitle">{token?'Use a secure password you do not reuse elsewhere.':'We will send instructions if the email belongs to an account.'}</p></div><form className="auth-form" onSubmit={submit}>{token?<><label className="auth-field"><span>New password</span><input className="auth-input" type="password" value={password} onChange={(e)=>setPassword(e.target.value)} autoComplete="new-password"/></label><label className="auth-field"><span>Confirm password</span><input className="auth-input" type="password" value={confirmPassword} onChange={(e)=>setConfirmPassword(e.target.value)} autoComplete="new-password"/></label></>:<label className="auth-field"><span>Account email</span><input className="auth-input" type="email" value={email} onChange={(e)=>setEmail(e.target.value)} autoComplete="email" placeholder="you@example.com"/></label>}<button className="button" type="submit" disabled={loading}>{loading?'Please wait…':token?'Change password':'Send reset email'}</button></form><p className="auth-note">Remembered it? <Link to="/login">Back to sign in</Link></p></div></AuthLayout></div>;
}
