import React, { useEffect, useMemo, useRef, useState } from 'react';
import './Profile.css';

export interface User { id?: string; username: string; email: string; fullName: string; bio?: string; photoUrl?: string; password: string }
interface ProfileProps {
  user: User; onClose: () => void;
  onSave: (updated: User & { photoFile?: File | null }) => Promise<void> | void;
  onChangePassword?: (payload: { currentPassword: string; newPassword: string }) => Promise<void> | void;
  onDelete: () => Promise<void> | void; title?: string;
}

export default function Profile({ user, onClose, onSave, onDelete, title = 'Edit profile' }: ProfileProps) {
  const [visible, setVisible] = useState(false); const [username,setUsername]=useState(user.username); const [fullName,setFullName]=useState(user.fullName); const [bio,setBio]=useState(user.bio||''); const [photoUrl,setPhotoUrl]=useState(user.photoUrl); const [photoFile,setPhotoFile]=useState<File|null>(null); const [saving,setSaving]=useState(false); const [deleting,setDeleting]=useState(false); const [errors,setErrors]=useState<Record<string,string>>({}); const inputRef=useRef<HTMLInputElement>(null);
  const previewUrl=useMemo(()=>photoFile?URL.createObjectURL(photoFile):photoUrl,[photoFile,photoUrl]);
  const close=()=>{setVisible(false);window.setTimeout(onClose,150)};
  useEffect(()=>{setVisible(true);const previous=document.body.style.overflow;document.body.style.overflow='hidden';const key=(event:KeyboardEvent)=>{if(event.key==='Escape')close()};window.addEventListener('keydown',key);return()=>{document.body.style.overflow=previous;window.removeEventListener('keydown',key)}},[]);
  useEffect(()=>()=>{if(photoFile&&previewUrl?.startsWith('blob:'))URL.revokeObjectURL(previewUrl)},[photoFile,previewUrl]);
  const pick=(file:File|null)=>{if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){setErrors({photo:'Use a JPEG, PNG or WebP image up to 10 MB.'});return}setErrors({});setPhotoFile(file)};
  const submit=async(event:React.FormEvent)=>{event.preventDefault();const nextErrors:Record<string,string>={};if(!/^[a-zA-Z0-9_.-]{3,32}$/.test(username))nextErrors.username='Use 3-32 letters, numbers, dots, dashes or underscores.';if(!fullName.trim())nextErrors.fullName='Add your name.';if(Object.keys(nextErrors).length){setErrors(nextErrors);return}setSaving(true);try{await onSave({...user,username:username.trim(),fullName:fullName.trim(),bio:bio.trim(),photoUrl,photoFile,password:''});close()}catch(error){setErrors({form:error instanceof Error?error.message:'Unable to save your profile.'})}finally{setSaving(false)}};
  const remove=async()=>{if(!confirm('Delete your account and all of its content? This cannot be undone.'))return;setDeleting(true);try{await onDelete()}catch(error){setErrors({form:error instanceof Error?error.message:'Unable to delete your account.'});setDeleting(false)}};
  return <div className={`custom-popup ${visible?'visible':''}`} role="dialog" aria-modal="true" aria-labelledby="profile-title" onMouseDown={(event)=>{if(event.target===event.currentTarget)close()}}><form className="custom-popup-content profile-popup" onSubmit={submit}><header className="profile-header"><div><p className="page-eyebrow">Account</p><h2 id="profile-title">{title}</h2></div><button className="closeIcon" type="button" onClick={close} aria-label="Close profile">×</button></header><div className="profile-body"><div className="profile-photo-column"><div className="photo-preview">{previewUrl?<img src={previewUrl} alt="Profile preview"/>:<div className="photo-placeholder">{fullName.charAt(0).toUpperCase()||'B'}</div>}</div><div className="photo-actions"><button className="btn ghost" type="button" onClick={()=>inputRef.current?.click()}>Change</button><button className="btn ghost" type="button" onClick={()=>{setPhotoFile(null);setPhotoUrl(undefined)}}>Remove</button></div><input ref={inputRef} type="file" hidden accept="image/jpeg,image/png,image/webp" onChange={(event)=>pick(event.target.files?.[0]||null)}/>{errors.photo&&<small className="field-error">{errors.photo}</small>}</div><div className="profile-form-column"><label className="field"><span className="label">Username</span><input value={username} onChange={(e)=>setUsername(e.target.value)} maxLength={32} aria-invalid={Boolean(errors.username)}/>{errors.username&&<small className="field-error">{errors.username}</small>}</label><label className="field"><span className="label">Email</span><input value={user.email} readOnly/></label><label className="field"><span className="label">Display name</span><input value={fullName} onChange={(e)=>setFullName(e.target.value)} maxLength={100} aria-invalid={Boolean(errors.fullName)}/>{errors.fullName&&<small className="field-error">{errors.fullName}</small>}</label><label className="field"><span className="label">Bio</span><textarea value={bio} onChange={(e)=>setBio(e.target.value)} maxLength={280} rows={4} placeholder="Tell artists about your sound."/></label>{errors.form&&<div className="form-error" role="alert">{errors.form}</div>}</div></div><footer className="profile-footer"><button className="btn ghost" type="button" onClick={remove} disabled={saving||deleting}>{deleting?'Deleting…':'Delete account'}</button><div><button className="btn ghost" type="button" onClick={close} disabled={saving}>Cancel</button><button className="btn" type="submit" disabled={saving}>{saving?'Saving…':'Save changes'}</button></div></footer></form></div>;
}
