import React, { useEffect, useMemo, useState } from 'react';
import { Edit3, Plus, Search, Trash2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import UserSingleton from '../../Model/UserSingleton';
import { BeatPost, deleteBeat, fetchProducerPosts, updateBeat } from '../../Model/api/posts';
import BeatEditor from '../../components/BeatEditor/BeatEditor';
import CustomPopup from '../../components/Popup/CustomPopup';
import { CardSkeleton, EmptyState } from '../../components/States/EmptyState';
import { formatCompactNumber, getBeatId, getCoverUrl } from '../../utils/entities';
import './BeatsPage.css';

const PAGE_SIZE = 50;
export default function BeatsPage() {
  const username = UserSingleton.getInstance().getUsername(); const token = localStorage.getItem('token') || '';
  const [beats, setBeats] = useState<BeatPost[]>([]); const [loading, setLoading] = useState(true); const [loadingMore, setLoadingMore] = useState(false); const [hasMore, setHasMore] = useState(true); const [filter, setFilter] = useState(''); const [selectedBeat, setSelectedBeat] = useState<BeatPost | null>(null); const [message, setMessage] = useState(''); const [deleting, setDeleting] = useState<string | null>(null);
  useEffect(() => { const controller = new AbortController(); fetchProducerPosts(token, username, PAGE_SIZE, 0, controller.signal).then((data) => { setBeats(data); setHasMore(data.length === PAGE_SIZE) }).catch((error) => { if (!controller.signal.aborted) setMessage(error instanceof Error ? error.message : 'Unable to load beats.') }).finally(() => { if (!controller.signal.aborted) setLoading(false) }); return () => controller.abort() }, [token, username]);
  const visible = useMemo(() => { const query = filter.trim().toLowerCase(); return query ? beats.filter((beat) => [beat.title, beat.genre, beat.description, ...(beat.tags || []), ...(beat.moods || [])].filter(Boolean).join(' ').toLowerCase().includes(query)) : beats }, [beats, filter]);
  const save = async (payload: Parameters<typeof updateBeat>[2]) => { if (!selectedBeat) return; const updated = await updateBeat(token, getBeatId(selectedBeat), payload); setBeats((items) => items.map((beat) => getBeatId(beat) === getBeatId(updated) ? { ...beat, ...updated } : beat)); setSelectedBeat(null); setMessage('Beat updated.') };
  const remove = async (beat: BeatPost) => { const id = getBeatId(beat); if (!confirm(`Delete “${beat.title}”? This cannot be undone.`) || deleting) return; setDeleting(id); try { await deleteBeat(token, id); setBeats((items) => items.filter((item) => getBeatId(item) !== id)); setMessage('Beat deleted.') } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to delete this beat.') } finally { setDeleting(null) } };
  const loadMore = async () => { if (loadingMore) return; setLoadingMore(true); try { const next = await fetchProducerPosts(token, username, PAGE_SIZE, beats.length); setBeats((items) => [...items, ...next]); setHasMore(next.length === PAGE_SIZE) } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to load more beats.') } finally { setLoadingMore(false) } };
  return <div className="page beats-page"><header className="page-header"><div><p className="page-eyebrow">Your catalog</p><h1 className="page-title">My beats</h1><p className="page-subtitle">Keep artwork and metadata sharp across your published catalog.</p></div><Link className="button" to="/upload"><Plus size={18} />Upload beat</Link></header><div className="catalog-toolbar"><label><Search size={18} /><span className="sr-only">Filter beats</span><input value={filter} onChange={(e) => setFilter(e.target.value)} placeholder="Filter by title, tag or genre" /></label><div><span><strong>{beats.length}</strong> beats</span><span><strong>{formatCompactNumber(beats.reduce((sum, beat) => sum + beat.likes, 0))}</strong> likes</span><span><strong>{formatCompactNumber(beats.reduce((sum, beat) => sum + (beat.views || beat.plays || 0), 0))}</strong> plays</span></div></div>
  {loading ? <CardSkeleton count={6} /> : visible.length === 0 ? <EmptyState title={beats.length ? 'No matches' : 'Your catalog is empty'} message={beats.length ? 'Try another search.' : 'Upload your first beat and start building your sound.'} action={!beats.length && <Link className="button" to="/upload">Upload beat</Link>} /> : <div className="catalog-list">{visible.map((beat) => <article className="catalog-row" key={getBeatId(beat)}><img src={getCoverUrl(beat)} onError={(e) => { e.currentTarget.src = '/cover-fallback.svg' }} alt="" loading="lazy" /><div className="catalog-identity"><h2>{beat.title}</h2><p>{beat.genre || 'No genre'} · {beat.publication_date ? new Date(beat.publication_date).toLocaleDateString() : 'No date'}</p><div>{beat.bpm && <span>{beat.bpm} BPM</span>}{(beat.tags || []).slice(0, 3).map((tag) => <span key={tag}>{tag}</span>)}</div></div><dl><div><dt>Likes</dt><dd>{beat.likes}</dd></div><div><dt>Saves</dt><dd>{beat.saves}</dd></div><div><dt>Plays</dt><dd>{formatCompactNumber(beat.views || beat.plays || 0)}</dd></div></dl><div className="catalog-actions"><button type="button" onClick={() => setSelectedBeat(beat)}><Edit3 size={17} />Edit</button><button type="button" className="danger" onClick={() => remove(beat)} disabled={deleting === getBeatId(beat)}><Trash2 size={17} />{deleting === getBeatId(beat) ? 'Deleting…' : 'Delete'}</button></div></article>)}</div>}
  {!filter && hasMore && !loading && <div className="load-more"><button className="button button--secondary" type="button" onClick={loadMore} disabled={loadingMore}>{loadingMore ? 'Loading…' : 'Load more'}</button></div>}{selectedBeat && <BeatEditor beat={selectedBeat} onClose={() => setSelectedBeat(null)} onSave={save} />}{message && <CustomPopup message={message} onClose={() => setMessage('')} />}</div>;
}
